x-configs:
    - &policy
      restart: always
    - &logging
      logging:
          driver: "json-file"
          options:
              max-file: "5"
              max-size: 10m

services:
    db:
        image: postgres:13.1-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - .db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        <<: [*logging, *policy]